from enum import Enum
class StrEnum(str,Enum): pass
class Role(StrEnum): ADMIN='ADMIN'; MANAGER='MANAGER'; DEVOPS='DEVOPS'; VIEWER='VIEWER'
class Provider(StrEnum): AWS='AWS'; AZURE='AZURE'; GCP='GCP'
class ResourceType(StrEnum): COMPUTE='COMPUTE'; DATABASE='DATABASE'; STORAGE='STORAGE'; LOAD_BALANCER='LOAD_BALANCER'; CONTAINER='CONTAINER'
class Severity(StrEnum): INFO='INFO'; WARNING='WARNING'; CRITICAL='CRITICAL'
class RecommendationType(StrEnum): SCALE_UP='SCALE_UP'; SCALE_DOWN='SCALE_DOWN'; RIGHT_SIZE='RIGHT_SIZE'; COST_OPTIMIZATION='COST_OPTIMIZATION'; RESOURCE_ALLOCATION='RESOURCE_ALLOCATION'
class RecommendationStatus(StrEnum): NEW='NEW'; ACCEPTED='ACCEPTED'; DISMISSED='DISMISSED'; EXPIRED='EXPIRED'
class ActionType(StrEnum): SCALE_OUT='SCALE_OUT'; SCALE_IN='SCALE_IN'; RESIZE='RESIZE'; EXPAND_STORAGE='EXPAND_STORAGE'; START='START'; STOP='STOP'
class ActionStatus(StrEnum): PENDING_APPROVAL='PENDING_APPROVAL'; APPROVED='APPROVED'; EXECUTING='EXECUTING'; SUCCEEDED='SUCCEEDED'; FAILED='FAILED'; REJECTED='REJECTED'; BLOCKED='BLOCKED'; CANCELLED='CANCELLED'
class PolicyType(StrEnum): SAFETY_LIMIT='SAFETY_LIMIT'; APPROVAL_RULE='APPROVAL_RULE'
class Channel(StrEnum): EMAIL='EMAIL'; WHATSAPP='WHATSAPP'; IN_APP='IN_APP'
class NotificationEvent(StrEnum): ALERT_CREATED='ALERT_CREATED'; RECOMMENDATION_CREATED='RECOMMENDATION_CREATED'; APPROVAL_REQUESTED='APPROVAL_REQUESTED'; ACTION_COMPLETED='ACTION_COMPLETED'; ACTION_FAILED='ACTION_FAILED'; BUDGET_THRESHOLD='BUDGET_THRESHOLD'; COST_ANOMALY='COST_ANOMALY'
