"""Deterministic, number-safe fallback responses for the AI layer."""

from datetime import datetime, timezone
from uuid import uuid4
from app.schemas.ai import AiExplanation, AiSummary, AiChatReply


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def generate_fallback_explanation(resource_name: str = "the selected resource", **_: object) -> AiExplanation:
    return AiExplanation(
        explanation=f"The AI service is unavailable right now. Review the current engine-generated details for {resource_name}; no new figures were generated by the fallback.",
        key_points=["The deterministic fallback is active.", "Cost, policy and metric values must be taken from the platform engines."],
        generated_at=_now(),
    )


def generate_fallback_summary(scope: str = "DASHBOARD", **_: object) -> AiSummary:
    return AiSummary(
        summary=f"The AI service is unavailable right now. The {scope.lower()} view remains available from the platform APIs.",
        highlights=["No unsupported figures are generated by the fallback."],
        generated_at=_now(),
    )


def generate_fallback_chat_reply(message: str, conversation_id: str | None = None, **_: object) -> AiChatReply:
    return AiChatReply(
        conversation_id=conversation_id or f"conv-{uuid4().hex[:8]}",
        reply="The AI service is temporarily unavailable. I can only provide information returned by the CloudOps read APIs; no action was executed.",
        suggested_actions=[],
    )
